server:
  port: 3001

spring:
  application:
    name: ms-reservas
  datasource:
    url: jdbc:postgresql://postgres:5432/microsmart_db
    username: admin
    password: admin_password
    # Principio menor privilegio: se debe configurar en Postgres un usuario con accesos restringidos para este MS
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: password
