version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ms_user
      POSTGRES_PASSWORD: ms_password
      POSTGRES_DB: microsmart_db

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    env_file:
      - ./api-gateway/.env
    depends_on:
      - ms-reservas
      - ms-solicitudes
      - ms-personalizacion

  ms-reservas:
    build: ./ms-reservas
    ports:
      - "3001:3001"
    env_file:
      - ./ms-reservas/.env
    depends_on:
      - postgres
      - rabbitmq

  ms-solicitudes:
    build: ./ms-solicitudes
    ports:
      - "3002:3002"
    env_file:
      - ./ms-solicitudes/.env
    depends_on:
      - rabbitmq

  ms-personalizacion:
    build: ./ms-personalizacion
    ports:
      - "3003:3003"
    env_file:
      - ./ms-personalizacion/.env
    depends_on:
      - mongodb
