server:
  port: 3000

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: redis
      port: 6379
  cloud:
    gateway:
      routes:
        - id: ms-reservas
          uri: http://ms-reservas:3001
          predicates:
            - Path=/api/reservas/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 100
                redis-rate-limiter.burstCapacity: 100
        - id: ms-solicitudes
          uri: http://ms-solicitudes:3002
          predicates:
            - Path=/api/solicitudes/**
        - id: ms-personalizacion
          uri: http://ms-personalizacion:3003
          predicates:
            - Path=/api/personalizacion/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://auth-server/.well-known/jwks.json" # URI a las llaves públicas para validar JWT
